# Generated by Django 5.0.6 on 2024-05-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('prenom', models.CharField(max_length=100)),
                ('deuxiemeprenom', models.CharField(max_length=100, null=True)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('telephone', models.CharField(max_length=50, unique=True)),
                ('commission', models.CharField(max_length=50)),
                ('estPresent', models.BooleanField(default=False)),
                ('enAttente', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'organisations',
            },
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('civilite', models.CharField(choices=[('M.', 'M.'), ('Mme.', 'Mme.'), ('Dr.', 'Dr.'), ('Pr.', 'Pr.')], max_length=5)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('deuxiemeprenom', models.CharField(blank=True, max_length=100)),
                ('organisme', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=100)),
                ('email1', models.CharField(max_length=50, unique=True)),
                ('email2', models.CharField(blank=True, max_length=50)),
                ('telephone', models.CharField(max_length=50, unique=True)),
                ('adresse', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=50)),
                ('pays', models.CharField(max_length=50)),
                ('organePresse', models.CharField(max_length=100, null=True)),
                ('lettreAutorisation', models.TextField(null=True)),
                ('typeTv', models.BooleanField(default=False)),
                ('typeRadio', models.BooleanField(default=False)),
                ('typeEcrite', models.BooleanField(default=False)),
                ('forumDesJeunes', models.BooleanField(default=False)),
                ('forumDesFemmes', models.BooleanField(default=False)),
                ('forumScientifiques', models.BooleanField(default=False)),
                ('estPresent', models.BooleanField(default=False)),
                ('enAttente', models.BooleanField(default=False)),
                ('provenance', models.CharField(max_length=50)),
                ('autreDocument', models.BooleanField(default=False)),
                ('lettreInvitation', models.BooleanField(default=False)),
                ('priseChargeBillet', models.BooleanField(default=False)),
                ('priseChargeComplete', models.BooleanField(default=False)),
                ('priseChargeHebergement', models.BooleanField(default=False)),
                ('reservationHotel', models.BooleanField(default=False)),
                ('priseChargetransUrbain', models.BooleanField(default=False)),
                ('autrePrecision', models.TextField(blank=True, max_length=1000)),
                ('autrePrecisionCharge', models.TextField(blank=True, max_length=1000)),
                ('dateDepart', models.DateField(null=True)),
                ('dateRetour', models.DateField(null=True)),
                ('villeDepart', models.CharField(max_length=100, null=True)),
                ('villeRetour', models.CharField(max_length=100, null=True)),
                ('passport', models.TextField(null=True)),
                ('biographie', models.TextField(max_length=1500, null=True)),
                ('photo', models.TextField(null=True)),
                ('is_presses', models.BooleanField(default=False)),
                ('isSpeakers', models.BooleanField(default=False)),
                ('isParticipants', models.BooleanField(default=False)),
                ('isEtudiants', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'participants',
            },
        ),
    ]
