# Generated by Django 3.2.8 on 2024-05-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('deuxiemeprenom', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('telephone', models.CharField(max_length=50, unique=True)),
                ('organePresse', models.CharField(max_length=100)),
                ('lettreAutorisation', models.TextField()),
                ('typeTv', models.BooleanField(default=False)),
                ('typeRadio', models.BooleanField(default=False)),
                ('typeEcrite', models.BooleanField(default=False)),
                ('estPresent', models.BooleanField(default=False)),
                ('enAttente', models.BooleanField(default=False)),
                ('provenance', models.CharField(max_length=50)),
                ('autreDocument', models.BooleanField(default=False)),
                ('lettreInvitation', models.BooleanField(default=False)),
                ('priseChargeBillet', models.BooleanField(default=False)),
                ('priseChargeComplete', models.BooleanField(default=False)),
                ('priseChargeHebergement', models.BooleanField(default=False)),
                ('reservationHotel', models.BooleanField(default=False)),
                ('priseChargetransUrbain', models.BooleanField(default=False)),
                ('autrePrecision', models.TextField(blank=True, max_length=1000)),
                ('autrePrecisionCharge', models.TextField(blank=True, max_length=1000)),
                ('dateDepart', models.DateField(null=True)),
                ('dateRetour', models.DateField(null=True)),
                ('villeDepart', models.CharField(max_length=100, null=True)),
                ('villeRetour', models.CharField(max_length=100, null=True)),
                ('passport', models.TextField(null=True)),
            ],
            options={
                'db_table': 'presses',
            },
        ),
        migrations.RemoveField(
            model_name='participants',
            name='is_presses',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='lettreAutorisation',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='organePresse',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='typeEcrite',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='typeRadio',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='typeTv',
        ),
    ]
