# Generated by Django 5.0.6 on 2024-07-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_alter_organisations_enattente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisations',
            name='civilite',
            field=models.CharField(choices=[('M.', 'M.'), ('Mme.', 'Mme.'), ('Dr.', 'Dr.'), ('Pr.', 'Pr.')], default='M.', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presses',
            name='civilite',
            field=models.CharField(choices=[('M.', 'M.'), ('Mme.', 'Mme.'), ('Dr.', 'Dr.'), ('Pr.', 'Pr.')], default='M.', max_length=5),
            preserve_default=False,
        ),
    ]
