# Generated by Django 5.0.6 on 2024-07-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_organisations_civilite_presses_civilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='isRemercimentsSend',
            field=models.BooleanField(default=False),
        ),
    ]
