# Generated by Django 5.0.6 on 2024-07-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_participants_isremercimentssend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='villeDepart',
            field=models.CharField(blank=True, default='inconnue', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participants',
            name='villeRetour',
            field=models.CharField(blank=True, default='inconnue', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='presses',
            name='villeDepart',
            field=models.CharField(blank=True, default='inconnue', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='presses',
            name='villeRetour',
            field=models.CharField(blank=True, default='inconnue', max_length=100, null=True),
        ),
    ]
