# Generated by Django 5.0.6 on 2024-07-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_alter_participants_villedepart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='villeDepart',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participants',
            name='villeRetour',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='presses',
            name='villeDepart',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='presses',
            name='villeRetour',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
