# Generated by Django 5.0.6 on 2024-08-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0008_alter_participants_villedepart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='villeRetour',
        ),
        migrations.RemoveField(
            model_name='presses',
            name='villeRetour',
        ),
        migrations.AddField(
            model_name='organisations',
            name='lang',
            field=models.CharField(choices=[('Fr', 'Fr'), ('En', 'En')], default='Fr', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participants',
            name='lang',
            field=models.CharField(choices=[('Fr', 'Fr'), ('En', 'En')], default='Fr', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presses',
            name='lang',
            field=models.CharField(choices=[('Fr', 'Fr'), ('En', 'En')], default='Fr', max_length=5),
            preserve_default=False,
        ),
    ]
